image: openjdk:15-alpine

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

stages:
  - build
  - test
  - check
  - deploy

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

Compile:
  stage: build
  script:
    - './gradlew --build-cache classes'

Test:
  stage: test
  script:
    - './gradlew test'

Check:
  stage: check
  script:
    - './gradlew --build-cache check'

Deploy:
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
  stage: deploy
  script:
    - './gradlew --build-cache publish'
