image: openjdk:15-alpine

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

stages:
  - build
  - test
  - check
  - deploy

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

Compile:
  stage: build
  except:
    - tags
  script:
    - './gradlew --build-cache classes'

Test:
  stage: test
  except:
    - tags
  script:
    - './gradlew test'

Check:
  stage: check
  except:
    - tags
  script:
    - './gradlew --build-cache check'

Deploy:
  stage: deploy
  except:
    - tags
  before_script:
    - url_host=`git remote get-url origin | sed -e "s/https:\/\/gitlab-ci-token:.*@//g"`
  script:
    - 'git remote set-url origin "https://$GIT_ACCESS_USER:$GIT_ACCESS_PASSWORD@${url_host}"'
    - 'git config user.name $GIT_ACCESS_USER'
    - 'git config user.email $GIT_ACCESS_EMAIL'
    - './gradlew --build-cache publish final -Prelease.scope=patch'
